find_worker_homepage:
    path:     /homepage
    defaults: { _controller: FindWorkerBundle:Main:homepage }

find_worker_contact:
    path:     /contact
    defaults: { _controller: FindWorkerBundle:Main:contact }

# Jeu de route projects
find_worker:
    resource: "@FindWorkerBundle/Resources/config/routing/project.yml"
    prefix:   /projects

# Jeu de route profiles
find_worker_profiles:
    resource: "@FindWorkerBundle/Resources/config/routing/profile.yml"
    prefix:   /profiles