findWorker:
    resource: "@FindWorkerBundle/Resources/config/routing.yml"
    prefix:   /

apis:
    resource: "@ApisBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
